flights/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index,name="index"),
    path("<int:flight_id>",views.flight,name="flight"),
    path("<int:flight_id>/book",views.book,name="book")
]

frontend/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "frontend"
urlpatterns = [
    path("", views.index, name = "index"),
    path("counter", views.counter, name="counter"),
    path("colors",views.colors, name="colors"),
    path("tasks",views.tasks, name="tasks"),
    path("currency",views.currency, name="currency"),
    path("animate",views.animate, name="animate"),
    path("react",views.react,name="react")
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hello/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("",views.index,name="index"),
    path("<str:name>", views.greet, name="greet")
]

myProject/urls.py
from django import urls
import django
from django.contrib import admin
from django.contrib.admin.sites import site
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/',include("newyear.urls")),
    path('tasks/',include("tasks.urls")),
    path('flights/',include("flights.urls")),
    path('users/',include("users.urls")),
    path('frontend/',include("frontend.urls"))
]

newyear/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("",views.index,name="index")
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name = "index"),
    path("add", views.add, name = "add")
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("", views.index, name = "index"),
    path("login", views.login_view, name = "login"),
    path("logout",views.logout_view, name="logout")
]

flights/models.py
from django.db import models
from django.db.models.deletion import CASCADE

# Create your models here.
class Airport(models.Model):
    code = models.CharField(max_length=3)
    city = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.city} ({self.code})"

class Flight(models.Model):
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="departures")
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="arrivals")
    duration = models.IntegerField()

    def __str__(self):
        return f"{self.id}: {self.origin} to {self.destination}"

    def is_valid_flight(self):
        return self.origin != self.destination and self.duration >= 0

class Person(models.Model):
    first = models.CharField(max_length=64)
    last = models.CharField(max_length=64)
    flights = models.ManyToManyField(Flight, blank=True, related_name="passengers")

    def __str__(self):
        return f"{self.first} {self.last}"

frontend/models.py
from django.db import models

# Create your models here.

hello/models.py
from django.db import models

# Create your models here.

newyear/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.

flights/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import Flight, Person

# Create your views here.
def index(request):
    return render(request,"flights/index.html",{
        "flights":Flight.objects.all()
    })

def flight(request, flight_id):
    flight = Flight.objects.get(pk=flight_id)
    return render(request,"flights/flight.html",{
        "flight": flight,
        "passengers": flight.passengers.all(),
        "non_passengers": Person.objects.exclude(flights = flight).all()
    })

def book(request, flight_id):
    if request.method == "POST":
        flight = Flight.objects.get(pk=flight_id)
        passenger = Person.objects.get(pk=int(request.POST["passenger"]))
        passenger.flights.add(flight)
        return HttpResponseRedirect(reverse("flight",args=(flight_id,)))

frontend/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "frontend/index.html")

def counter(request):
    return render(request, "frontend/counter.html")

def colors(request):
    return render(request,"frontend/colors.html")

def tasks(request):
    return render(request,"frontend/tasks.html")

def currency(request):
    return render(request,"frontend/currency.html")

def animate(request):
    return render(request,"frontend/animate.html")

def react(request):
    return render(request,"frontend/react.html")

hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def greet2(request,name):
    return HttpResponse(f"Hello, {name.title()}!")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name": name.title()
    })

newyear/views.py
import datetime
from django.shortcuts import render

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request,"newyear/index.html",{
        "newyear": now.month == 1 and now.year == 1
    })

tasks/views.py
from django.urls import reverse
from django.http.response import HttpResponseRedirect
import tasks
from django import forms
from django.shortcuts import render

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
    priority = forms.IntegerField(label="Priority",min_value=10,max_value=100)

# tasks = ["foo","bar","baz"]
# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []
    return render(request, "tasks/index.html",{
        "tasks": request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request,"tasks/add.html",{
                "form": form
            })

    return render(request,"tasks/add.html",{
        "form": NewTaskForm()
    })

users/views.py
from django.contrib.auth import authenticate,login,logout
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    return render(request,"users/user.html")

def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username,password=password)
        if user is not None:
            login(request,user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "users/login.html",{
                "message": "Invalid Credentials"
            })
    return render(request, "users/login.html")

def logout_view(request):
    logout(request)
    return render(request, "users/login.html",{
        "message": "Logged Out"
    })

flights/templates/flights/flight.html
{% extends "flights/layout.html" %}

{% block body %}
    <h1>Flight {{ flight.id }}</h1>
    <ul>
        <li>Origin: {{ flight.origin }}</li>
        <li>Destination: {{ flight.destination }}</li>
        <li>Duration: {{ flight.duration }} minutes</li>
    </ul>

    <h2>Passengers</h2>
    <ul>
        {% for passenger in passengers %}
            <li>{{ passenger }}</li>
        {% empty %}
            <h3>NO PASSENGERS</h3>
        {% endfor %}
    </ul>

    <h2>Add Passenger</h2>
    <form action="{% url 'book' flight.id %}" method="POST">
        {% csrf_token %}
        <select name="passenger">
            {% for passenger in non_passengers %}
                <option value="{{ passenger.id }}">{{ passenger }}</option>
            {% endfor %}
        </select>
        <input type="submit">
    </form>
    <a href="{% url 'index' %}">All Flights</a>
{% endblock %}

flights/templates/flights/index.html
{% extends "flights/layout.html" %}

{% block body %}
    <h1>Flights:</h1>
    <ul>
        {% for flight in flights %}
            <li><a href="{% url 'flight' flight.id %}">Flight {{ flight.id }}</a>: {{ flight.origin }} to {{ flight.destination }}</li>
        {% endfor %}
    </ul>
{% endblock %}

flights/templates/flights/layout.html
<!doctype html>
<html lang="en">
  <head>
    <title>Flight data</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
      {% block body %}
      {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

frontend/templates/frontend/animate.html
{% extends 'frontend/layout.html' %} {% block body %}

<style>
    @keyframes move {
        0%{
            left: 0%;
        }
        50%{
            left: 50%;
        }
        100%{
            left: 0%;
        }
    }
    h1{
        position: relative;
        animation-name: move;
        animation-duration: 2s;
        animation-fill-mode: forwards;
        animation-iteration-count: infinite;
    }
</style>
<script> document.addEventListener('DOMContentLoaded', () => {
    const h1 = document.querySelector('h1');
    h1.style.animationPlayState = "paused";

    document.querySelector('button').onclick = () => {
        if(h1.style.animationPlayState === 'paused'){
            h1.style.animationPlayState = 'running';
        }else {
            h1.style.animationPlayState = 'paused';
        };
    };
});
</script>

<button>Click Here!</button>

<h1>Welcome!</h1>

{% endblock %}

frontend/templates/frontend/colors.html
{% extends 'frontend/layout.html' %}

{% block body %}

<script>
    // document.addEventListener('DOMContentLoaded',() => {
    //     document.querySelectorAll('button').forEach(button => {
    //         button.onclick = function(){
    //             document.querySelector('#hello').style.color = button.dataset.color
    //         }
    //     });
    // });
    document.addEventListener('DOMContentLoaded',() => {
        document.querySelector('select').onchange = function() {
            document.querySelector('#hello').style.color = this.value
        };
    });

</script>
<h1 id="hello"> Hello!</h1>
<!-- <button data-color='red'>Red</button>
<button data-color='green'>Green</button>
<button data-color='blue'>Blue</button> -->
<select >
    <option value="black">Black</option>
    <option value="red">Red</option>
<option value="green">Green</option>
<option value="blue">Blue</option>
</select>

{% endblock %}

frontend/templates/frontend/counter.html
<head>
    <script crossorigin src="https://unpkg.com/react@17/umd/react.development.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@17/umd/react-dom.development.js"></script>
    <script crossorigin src="https://unpkg.com/babel-standalone@6.26.0/babel.min.js"></script>
</head>
<style>
    #app {
        text-align: center;
    }

    #problem {
        font-size: 72px;
    }

    #winner {
        font-size: 72px;
        color: green;
    }
</style> 
{% extends 'frontend/layout.html' %} 



{% block body %}
<h1>Counter</h1>
{% load static %}
<div id="app">
    <script type="text/babel" src="{% static 'frontend/counter.jsx' %}"></script>

</div>

{% endblock %}

frontend/templates/frontend/currency.html
{% extends 'frontend/layout.html' %} {% block body %}
<script>
    document.addEventListener("DOMContentLoaded", () => {
        document.querySelector("form").onsubmit = () => {
            fetch("https://api.exchangeratesapi.io/latest?base=USD")
                .then((response) => response.json())
                .then((data) => {
                    const currency = document.querySelector('#currency').value.toUpperCase();
                    const rate = data.rates[currency];
                    if(rate !== undefined){
                        document.querySelector("#result").innerHTML = `1 USD = ${rate.toFixed(3)} ${currency}`;
                    }else{
                        document.querySelector("#result").innerHTML = `Invalid Currency: ${currency}`; 
                    }
                })
                .catch(error => {
                    console.log('Error:', error);
                });
                return false;
        };
    });
</script>

<form>
    <input id="currency" placeholder="Currency" type="text">
    <input type="submit" value="Convert">
</form>
<div id="result"></div>

{% endblock %}

frontend/templates/frontend/index.html
{% extends 'frontend/layout.html' %}

{% block body %}
<h1>Hello World!</h1>
<script>
    // function hello(){
    //     // alert('Hello, World');
    //     if (document.querySelector('h1').innerHTML === "Hello World!"){
    //         document.querySelector('h1').innerHTML = "Goodbye!";
    //     }
    //     else {
    //         document.querySelector('h1').innerHTML = "Hello World!";
    //     }
    // }

    document.addEventListener('DOMContentLoaded',function(){
        document.querySelector('form').onsubmit = function(){
            const name = document.querySelector('#name').value;
            alert(`Hello ${name}`)
        };
    });
</script>
<!-- <button class="btn btn-primary" onclick="hello()">Click here!</button> -->
<a name="" id="" class="btn btn-secondary" href="{% url 'frontend:counter' %}" role="button">Counter</a>
<form>
    <input autofocus id="name" placeholder="Name" type="text">
    <input type="submit">
</form>

{% endblock %}

frontend/templates/frontend/layout.html
<!doctype html>
<html lang="en">
  <head>
    <title>Javascript tests</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
      {% block body %}

      {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

frontend/templates/frontend/react.html
<head>
    <script crossorigin src="https://unpkg.com/react@17/umd/react.development.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@17/umd/react-dom.development.js"></script>
    <script crossorigin src="https://unpkg.com/babel-standalone@6.26.0/babel.min.js"></script>
</head>
{% extends 'frontend/layout.html' %}


{% block body %}

<body> 
    <div id="app">
        <script type="text/babel">

        class Hello extends React.Component{
            render(){
                return(
                    <h1>Hello, {this.props.name}! </h1>
                )
            }
        }

        class App extends React.Component {

            render() {
                return (
                    <div>
                        <Hello name="Harry"/>
                        <Hello name="Ron"/>
                        <Hello name="Draco"/> 
                    </div>
                );
            }
        }
        
        ReactDOM.render(<App />,document.querySelector('#app'));

        </script>
    </div>
</body>

{% endblock %}

frontend/templates/frontend/tasks.html
{% extends 'frontend/layout.html' %}

{% block body %}
<script>
    document.addEventListener('DOMContentLoaded',() => {
        document.querySelector('form').onsubmit = () => {

            document.querySelector('#submit').disabled = true;

            document.querySelector('#task').onkeyup = () => {
                if (document.querySelector('#task').value.length > 0){
                    document.querySelector('#submit').disabled = false;
                }else{
                    document.querySelector('#submit').disabled = true;
                }
                
            }

            const task = document.querySelector('#task').value;

            const li = document.createElement('li');

            li.innerHTML = task;

            document.querySelector('#tasks').append(li);
            document.querySelector('#task').value = '';
            document.querySelector('#submit').disabled = true;

            return false;
        };
    });
</script>

<h1>Tasks</h1>
<ul id='tasks'> </ul>
<form>
    <input id="task" placeholder="New Task" type="text">
    <input id = 'submit' type="submit">
</form>

{% endblock %}

hello/templates/hello/greet.html
<!doctype html>
<html lang="en">
  <head>
    <title>Greetings! {{ name }}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>

    <h1>Hello {{ name }}!</h1>
      
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

hello/templates/hello/index.html
<!doctype html>
<html lang="en">
  <head>
    <title>My Django app</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>

    <h1>Hello World!</h1>
      
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

newyear/templates/newyear/index.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <title>Is It New Year's?</title>
    <link href='{% static "newyear/styles.css" %}' rel="stylesheet">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
  </head>
  <body>
      {% if newyear %}
            <h1>YES</h1>
      {% else %}
            <h1>NO</h1>
        {% endif %}
      
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->
  </body>
</html>

tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %} {% block body %}
<h1>Add Task:</h1>
<form action="{% url 'tasks:add' %}" method="POST">
  {% csrf_token %}
  {{ form }}
  <!-- <input type="text" name="task" /> -->
  <input type="submit" />
</form>
<a href="{% url 'tasks:index' %}">View Tasks</a>
{% endblock %}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %} {% block body %}
<h1>Tasks</h1>
<ul>
  {% for task in tasks %}
  <li>{{ task }}</li>
  {% empty %}
  <h3>No Tasks</h3>
  {% endfor %}
</ul>
<a href="{% url 'tasks:add' %}">Add Task</a>
{% endblock %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Tasks</title>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
  </head>
  <body>
    {% block body%} {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

users/templates/users/layout.html
<!doctype html>
<html lang="en">
  <head>
    <title>User</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>

    {% block body %}

    {% endblock %}
      
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

users/templates/users/login.html
{% extends 'users/layout.html' %} 
{% block body %} 
{% if message %}
<div>{{ message }}</div>
{% endif %}
<form action="{% url 'login' %}" method="post">
  {% csrf_token %}
  <input type="text" name="username" placeholder="username">
  <input type="password" name="password" placeholder="password">
  <input type="submit" value="Login">
 </form>
  {% endblock %}

users/templates/users/user.html
{% extends "users/layout.html" %}

{% block body %}
    <h1>Welcome, {{ request.user.first_name }}</h1>
    <ul>
        <li>Username: {{ request.user.username }}</li>
        <li>Email: {{ request.user.email }}</li>
    </ul>

    <a href="{% url 'logout' %}">Log Out</a>
{% endblock %}